### ISSUE TITLE
Long time for building

### ISSUE THREAD

**Issue by hyavari** [ugoviti/izdock-izpbx#10]
Hi Ugo,
Do you think it's better to install Asterisk from packages to make the building process faster?

BR.

**Comment by ugoviti** [comment]
Hi Yavari,

thank you for your feedback... Why do you need to rebuild the image?

We recompile Asterisk from scratch because:

1. We want control the build process
2. No official CentOS 8 Asterisk packages are available or not always in sync with upstream official release

If you want use izpbx as base image you don't need to rebuild every time, just reference it in you Dockerfile as

`FROM izdock/izpbx-asterisk:VERSION`

Here all available tags:

https://hub.docker.com/repository/docker/izdock/izpbx-asterisk/tags?page=1&ordering=last_updated

Kind Regards
