### ISSUE TITLE
running issue

### ISSUE THREAD

**Issue by hyavari** [ugoviti/izdock-izpbx#11]
Hi Ugo,

Have u checked the last codes? I tried to build and run. There are some points:

docker run --rm -ti --network=host --privileged --cap-add=NET_ADMIN -v ./data/izpbx:/data -e MYSQL_ROOT_PASSWORD=CHANGEM3 -e MYSQL_PASSWORD=CHANGEM3 -e MYSQL_SERVER=127.0.0.1 -e MYSQL_DATABASE=asterisk -e MYSQL_USER=asterisk -e APP_DATA=/data --name izpbx izpbx-asterisk:latest

MYSQL_SERVER is not 127.0.0.1. We have to get it from container inspect, right??

Then, it couldn't connect to DB with asterisk user:
Invalid Database Permissions. The error was: SQLSTATE[HY000] [1045] Access denied for user 'asterisk'@'172.17.0.1' (using password: YES)

Please let me know if I am running it wrongly.

BR

**Comment by ugoviti** [comment]
Hi Yavari,

as stated into README.md the suggested fast and easy method to running izpbx is using `docker-compose`.

Of course, for development purpose you can also build it and run from scratch (time consuming).

If you don't want use docker-compose, you must start mariadb before starting izpbx.

In your command I don't see the docker run for mariadb database, have a mariadb/mysql database running? 

"only" for development purpose you can follow that README:
https://github.com/ugoviti/izdock-izpbx/blob/dev/izpbx-asterisk/README.md

I just enanched the commands to run in sequence (just tryed):

### Docker Run:
Start MySQL:  
`docker run --rm -ti -p 3306:3306 -v ${PWD}/data/db:/var/lib/mysql -e MYSQL_DATABASE=asterisk -e MYSQL_USER=asterisk -e MYSQL_ROOT_PASSWORD=CHANGEM3 -e MYSQL_PASSWORD=CHANGEM3 --name izpbx-db mariadb:10.5`

Start izPBX:  
`docker run --rm -ti --network=host --privileged --cap-add=NET_ADMIN -v ${PWD}/data/izpbx:/data -e MYSQL_SERVER=127.0.0.1 -e MYSQL_DATABASE=asterisk -e MYSQL_USER=asterisk -e MYSQL_ROOT_PASSWORD=CHANGEM3 -e MYSQL_PASSWORD=CHANGEM3 -e APP_DATA=/data --name izpbx izpbx-asterisk:dev-18`

Otherwise, follow the official enduser README please: 
https://github.com/ugoviti/izdock-izpbx/blob/dev/README.md

Thankyou for your feedback.

Kind Regards
