### ISSUE TITLE
[suggestion] Enabling TLS in Postfix

### ISSUE THREAD

**Issue by fa-at-pulsit** [ugoviti/izdock-izpbx#9]
It would be nice to add STARTTLS support for Postfix
e.g. new variables like
**SMTP_STARTTLS** 
**SMTP_RELAYHOST_PORT** (that we need for main.cf but not for sasl_password)

if true add to **/etc/postfix/main.cf**
```
smtp_use_tls=yes
relayhost = my.mail.server.com:${SMTP_RELAYHOST_PORT}
```
and in **/etc/postfix/sasl_passwd** just
```
${SMTP_RELAYHOST} ${SMTP_RELAYHOST_USERNAME}:${SMTP_RELAYHOST_PASSWORD}
```

**Comment by ugoviti** [comment]
Hi, sorry for late reply...

Thank you for the suggestion... I think SMTP_RELAYHOST_PORT is not required because for example you can use directly:

`SMTP_RELAYHOST=[smtp.example.com]:587`

pushed right now in dev commit c956becf50be197ef55b100f1479f31a4bde921d and 18.15.2 release (building now)

please make a try and let me know if working good.

Kinds regards
